### ISSUE TITLE
Error using using deno-postgres but query works directly in cli

### ISSUE THREAD

**Issue by aviteller** [denodrivers/postgres#148]
Im trying to enter this query in my app:

`SELECT * FROM books AS b  JOIN (SELECT id,name FROM  users) u ON b.user_id = u.id  WHERE b.deleted_at is null  AND  b.slug  ILIKE '%the%'   LIMIT 10 OFFSET 0 `

i get back this error 

`Error: PostgresError: missing FROM-clause entry for table "b"
    at Book.DB.getAll (DB.ts:172:13)
    at async Book.getBooks (Book.ts:57:12)
    at async BookController.getBooks (books.ts:14:19)
    at async logger (logger.ts:11:3)
    at async server.ts:10:5
    at async Application.#handleRequest (application.ts:241:9)`

When i try it directly with pgadmin4 or the cli it works
Could be an issue

**Comment by Soremwar** [comment]
Wow this issue has quite some time on it. I'm the new mantainer

Have you encountered this issue with recent versions of the library?

**Comment by Soremwar** [comment]
Closing due to inactivity
