### ISSUE TITLE
Concurrent connect-then-release cycles break the pool

### ISSUE THREAD

**Issue by baoshan** [denodrivers/postgres#378]
Below code:
```ts
const pool = new Pool(databaseUrl, 1);
async function connectThenRelease(pool: Pool) {
  let client = await pool.connect();
  client.release();
  client = await pool.connect();
  client.release();
}
await Promise.all([
  connectThenRelease(pool),
  connectThenRelease(pool),
]);
```

Throws an exception:
```
TypeError: Cannot read properties of undefined (reading 'connected')
    at DeferredAccessStack.<anonymous> (https://deno.land/x/postgres@v0.15.0/pool.ts:205:26)
    at DeferredAccessStack.pop (https://deno.land/x/postgres@v0.15.0/utils/deferred.ts:121:48)
```

Please let me know if this is expected and if a PR is welcomed.

**Comment by Soremwar** [comment]
I would expect this to work, I'll look into it. PRs are always welcome
