### ISSUE TITLE
`deno check <file>` fails since Deno v1.29.0 for vendored deno-postgres

### ISSUE THREAD

**Issue by ChristianSiegert** [denodrivers/postgres#420]
**Steps to reproduce:**
1. Create a .ts file and import deno-postgres:
    ```ts
    // main.ts
    import "https://deno.land/x/postgres@v0.17.0/mod.ts";
    ```
2. Run `deno vendor main.ts`
3. Run `deno check --import-map=vendor/import_map.json main.ts`

**Expected:** No errors

**Actual:** Errors are reported for deno-postgres:
```
Check file:///<redacted>/main.ts
error: TS2345 [ERROR]: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    a: decodePoint(a),
                   ^
    at file:///<redacted>/vendor/deno.land/x/postgres@v0.17.0/query/decoders.ts:46:20

TS2345 [ERROR]: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    a: decodePoint(a),
                   ^
    at file:///<redacted>/vendor/deno.land/x/postgres@v0.17.0/query/decoders.ts:227:20

Found 2 errors.
```

Environment:
```
deno --version
deno 1.30.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by bombillazo** [comment]
I jsut tried it with the latest version, no error was reported and could not replicate this. Seems fixed
