### ISSUE TITLE
Interrupted: operation canceled

### ISSUE THREAD

**Issue by eikmei** [denodrivers/postgres#428]
Try to loop array in order to run delete query. Function as below.

```
wheres.forEach(async (where) => {
        const deleteSql = `DELETE FROM ${settings.toTable} WHERE ${where}`;
        try {
          await destinationClient.queryObject(deleteSql);
        } catch (err) {
          console.log("Error executing query:", err);
          await sourceClient.end();
        }
      })
```

But get this error

```
Error executing query: Interrupted: operation canceled
    at async TcpConn.read (deno:ext/net/01_net.js:80:17)
    at async BufReader.read (https://deno.land/std@0.114.0/io/buffer.ts:383:12)
    at async BufReader.readFull (https://deno.land/std@0.114.0/io/buffer.ts:415:20)
    at async Connection.#readMessage (https://deno.land/x/postgres@v0.15.0/connection/connection.ts:152:5)
    at async Connection.#simpleQuery (https://deno.land/x/postgres@v0.15.0/connection/connection.ts:672:27)
    at async Connection.query (https://deno.land/x/postgres@v0.15.0/connection/connection.ts:928:16)
```

**Comment by gliluaume** [comment]
Hello @eikmei,
Maybe it will work using a pool as described here: https://deno-postgres.com/#/?id=connection-pools
