### ISSUE TITLE
Sasl Authentication failed with Deno 1.34.3 (latest)

### ISSUE THREAD

**Issue by jannikkeye** [denodrivers/postgres#429]
I've encountered a similar issue as #412.

Target Database: Neon

I've tested with 1.25.4 and was able to connect and performa a query.

Testing again with 1.34.3 I get this error:

```
error: Uncaught PostgresError: password authentication failed for user 'jannikkeye'
        throw new PostgresError(parseNoticeMessage(maybe_sasl_final));
              ^
    at Connection.#authenticateWithSasl (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:654:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Connection.#authenticate (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:547:33)
    at async Connection.#startup (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:412:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:491:11)
    at async Client.connect (https://deno.land/x/postgres@v0.16.1/client.ts:220:7)
    at async file:///Users/jannikkeye/Code/polyscale/connection-checker/test/neon.ts:10:1
```

Trying to figure out when and why it stopped working. It appears to be related to the Sasl authentication. 

Did anything change here lately?

**Comment by jannikkeye** [comment]
If anyone runs into this as well there aren't really great alternatives.

I've tried npm:pg but that has other issues and in the end landed on https://deno.land/x/postgresjs. Only downside here is that it implicitly connects on first query but other than that it works great and its not really a downside for most use cases.

**Comment by bombillazo** [comment]
can you try with the latest version?

**Comment by jannikkeye** [comment]
Just tried with a minimal reproduction example and I am no longer seeing this error :) thanks for resolving
