### ISSUE TITLE
There is a bug in pool when connection cannot be established at pool start

### ISSUE THREAD

**Issue by langpavel** [denodrivers/postgres#478]
**Describe the bug**

There is a bug in pool when connection cannot be established at pool start.
This bug will bite when you wish close the connection

**To Reproduce**

1. Start your deno server
2. Start your pool
3. Try to connect
4. Exception happen (good)
5. **Start database**
6. Try to connect
7. Do insert (OK, commited)
8. **Release pool client**, then
8.5. **Exception happens.**
9. but query succeeds

**Expected behavior**

No exception

**This bug is not observed when database connection is ready at start**

**Comment by langpavel** [comment]
I think this is somewhere in `DeferredAccessStack`, but I have no proof, except this:

```
deno-server-1           | Insert successful
deno-server-1           | ERROR ConnectionRefused: Connection refused (os error 111)
deno-server-1           |     at async Object.connect (ext:deno_net/01_net.js:587:55)
deno-server-1           |     at async Connection.#openConnection (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:266:18)
deno-server-1           |     at async Connection.#startup (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:342:7)
deno-server-1           |     at async Connection.startup (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:494:11)
deno-server-1           |     at async PoolClient.connect (https://deno.land/x/postgres@v0.19.3/client.ts:233:7)
deno-server-1           |     at async DeferredAccessStack.pop (https://deno.land/x/postgres@v0.19.3/utils/deferred.ts:115:7)
deno-server-1           |     at async _custom_ (file:///home/deno/fake-device/_custom_.ts:51:26)
deno-server-1           |     at async Promise.all (index 2)
deno-server-1           |     at async file:///home/deno/main.ts:17:3 {
deno-server-1           |   name: "ConnectionRefused",
deno-server-1           |   code: "ECONNREFUSED"
deno-server-1           | }
```

**Comment by langpavel** [comment]
This will only happen when deno service is starterd before postgres.

**Comment by langpavel** [comment]
Don't know if related, but I'm using lazy mode.
